In [ ]:
# Installing python libraries
!pip install -U textblob
!python -m textblob.download_corpora

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: textblob in /usr/local/lib/python3.8/dist-packages (0.15.3)
Collecting textblob
  Downloading textblob-0.17.1-py2.py3-none-any.whl (636 kB)
     |████████████████████████████████| 636 kB 4.1 MB/s
Requirement already satisfied: nltk>=3.1 in /usr/local/lib/python3.8/dist-packages (from textblob) (3.7)
Requirement already satisfied: click in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (7.1.2)
Requirement already satisfied: joblib in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (2022.6.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.8/dist-packages (from nltk>=3.1->textblob) (4.64.1)
Installing collected packages: textblob
  Attempting uninstall: textblob
    Found existing installation: textblob 0.15.3
    Uninstalling textblob-0.15.3:
      Successfully uninstalled textblob-0.15.3
Successfully installed textblob-0.17.1
[nltk_data] Downloading package brown to /root/nltk_data...
[nltk_data]   Unzipping corpora/brown.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package conll2000 to /root/nltk_data...
[nltk_data]   Unzipping corpora/conll2000.zip.
[nltk_data] Downloading package movie_reviews to /root/nltk_data...
[nltk_data]   Unzipping corpora/movie_reviews.zip.
Finished.

In [ ]:
# Importing pandas and reading in webs scraped IMDB reviews file for episode 3
import pandas as pd
star_wars_3_df = pd.read_csv("/content/INST737_Star_Wars_IMDB_StarWars3.csv")

In [ ]:
# Prints the first few columns
star_wars_3_df.head()

,Unnamed: 0,Review_Date,Author,Rating,Review_Title,Review,Review_Url
0,0,12 December 2015,claudio_carvalho,10.0,The Final Part of the Saga\n,"In Coruscant, the Jedi Obi-Wan Kenobi (Ewan Mc...",/review/rw1328600/?ref_=tt_urv
1,1,19 December 2015,jaredpahl,9.0,"Epic, Emotional, and Powerful. George Lucas' ...",The final entry in George Lucas' Star Wars sag...,/review/rw1328600/?ref_=tt_urv
2,2,5 June 2018,BiiivAL,10.0,This is war\n,"May 19, 2005 was not a simple day for fans and...",/review/rw1328600/?ref_=tt_urv
3,3,28 September 2020,auuwws,10.0,Revenge of the Sith\n,One of the best star wars movies and best scen...,/review/rw1328600/?ref_=tt_urv
4,4,21 May 2005,classicsoncall,10.0,"""Revenge is a dish best served cold.""\n","And so, the Star Wars saga comes full circle, ...",/review/rw1328600/?ref_=tt_urv

In [ ]:
# Drops unneeded columns 
star_wars_3_df_v2 = star_wars_3_df.drop(columns = ["Review_Date", "Author", "Rating", "Review_Title", "Review_Url", "Unnamed: 0"])

In [ ]:
# Prints newly edited dataframe
star_wars_3_df_v2

                                                 Review
0     In Coruscant, the Jedi Obi-Wan Kenobi (Ewan Mc...
1     The final entry in George Lucas' Star Wars sag...
2     May 19, 2005 was not a simple day for fans and...
3     One of the best star wars movies and best scen...
4     And so, the Star Wars saga comes full circle, ...
...                                                 ...
3768  In Star Wars: Episode Three Anakin struggles b...
3769  Sith ain't great, everything promised by the d...
3770  Star Wars Episode III Revenge of the Sith Cast...
3771  Overall I liked. I think the story was one of ...
3772  IT COULD HAVE BEEN SO MUCH BETTER! When dookoo...

[3773 rows x 1 columns]

In [ ]:
# Test block to see if review gets printed
reviewParagraph = ""
for review in star_wars_3_df_v2['Review'][:1]:
  reviewParagraph = review

In [ ]:
# Prints results from previous test for loop 
reviewParagraph

"In Coruscant, the Jedi Obi-Wan Kenobi (Ewan McGregor) and Anakin Skywalker (Hayden Christensen) rescue the Supreme Chancellor Palpatine (Ian McDiarmid) from the Separatist General Grievous' spaceship and Anakin kills Count Dooku (Christopher Lee) with his light-saber after a fight; however Grievous escape from the Jedi. When they land on Coruscant, Padmé Amidala (Natalie Portman) comes to tell Anakin that she is pregnant. Soon he has premonitions of his wife dying during the delivery. Palpatine requests that Anakin joins the Jedi Council against the will of the members but his is not promoted to Master and stays Padawan; further they ask him to spy Palpaline. Anakin is manipulated by Palpatine about the true intentions of the Jedi and is tempted to know the dark side of the Force that could be capable to save Padmé. Further Palpatine discloses that he is Sith Lord Darth Sidious. What will Anakin do?"

In [ ]:
# Imports TextBlob
from textblob import TextBlob
blob = TextBlob(reviewParagraph)

In [ ]:
# This block was used for testing purposes to see if the first review's sentiment and polarity would get displayed
blob.sentiment

Sentiment(polarity=-0.09074074074074076, subjectivity=0.6055555555555556)

In [ ]:
# Creates dataframe that will be used to get the sentiment and polarity of all star wars episode 3 reviews
star_wars_episode_3_final_df = pd.DataFrame(columns = ['Review', 'Polarity', 'Subjectivity'])

In [ ]:
# Checks to see if dataframe was created with the columns created above 
star_wars_episode_3_final_df

Empty DataFrame
Columns: [Review, Polarity, Subjectivity]
Index: []

In [ ]:
# This block would give the polarity and subjectivity of all reviews for Star Wars episode 3
star_wars_review_list = []
star_wars_polarity_list = []
star_wars_subjectivity_list = []

for review in star_wars_3_df_v2['Review']:
  blob = TextBlob(str(review))
  star_wars_review_list.append(review)
  star_wars_polarity_list.append(blob.sentiment.polarity)
  star_wars_subjectivity_list.append(blob.sentiment.subjectivity)



star_wars_episode_3_final_df['Review'] = star_wars_review_list
star_wars_episode_3_final_df['Polarity'] = star_wars_polarity_list
star_wars_episode_3_final_df['Subjectivity'] = star_wars_subjectivity_list


star_wars_episode_3_final_df = star_wars_episode_3_final_df[['Review', 'Polarity', 'Subjectivity']]
  
star_wars_episode_3_final_df.head()

                                              Review  Polarity  Subjectivity
0  In Coruscant, the Jedi Obi-Wan Kenobi (Ewan Mc... -0.090741      0.605556
1  The final entry in George Lucas' Star Wars sag...  0.261905      0.535714
2  May 19, 2005 was not a simple day for fans and... -0.088889      0.506349
3  One of the best star wars movies and best scen...  1.000000      0.300000
4  And so, the Star Wars saga comes full circle, ...  0.222500      0.650000

In [ ]:
# Converting dataframe to csv 
# Code down below was commented out because file already created 
# star_wars_episode1_final_df.to_csv('Star_Wars_Episode3_Sentiment_Analysis.csv’)

In [ ]:
# Reviews that have a polarity greater than 0 go to a positive dataframe
positive_df = star_wars_episode_3_final_df[star_wars_episode_3_final_df['Polarity'] > 0]
positive_df

,Review,Polarity,Subjectivity
1,The final entry in George Lucas' Star Wars sag...,0.261905,0.535714
3,One of the best star wars movies and best scen...,1.000000,0.300000
4,"And so, the Star Wars saga comes full circle, ...",0.222500,0.650000
5,The first two movies in the prequel trilogy we...,0.188929,0.546130
6,Star Wars Episode 3 Revenge of the Sith is my ...,0.348889,0.527778
...,...,...,...
3766,"I came to this movie, like the rest of America...",0.266667,0.358333
3767,Not because the last and the most technologica...,0.186111,0.580093
3769,"Sith ain't great, everything promised by the d...",0.022300,0.509410
3771,Overall I liked. I think the story was one of ...,0.091468,0.581349
3772,IT COULD HAVE BEEN SO MUCH BETTER! When dookoo...,0.372426,0.564052

In [ ]:
# Reviews that have a polarity less than 0 go to a negative dataframe
negative_df = star_wars_episode_3_final_df[star_wars_episode_3_final_df['Polarity'] < 0]
negative_df

,Review,Polarity,Subjectivity
0,"In Coruscant, the Jedi Obi-Wan Kenobi (Ewan Mc...",-0.090741,0.605556
2,"May 19, 2005 was not a simple day for fans and...",-0.088889,0.506349
16,Finally we have the episode3 of Star wars. So ...,-0.111210,0.562202
23,"I know a lot hates the Prequels, for a lot of ...",-0.055556,0.344444
27,When George Lucas announced over 10 years ago ...,-0.015278,0.389815
...,...,...,...
3741,To start off the opening scene was a bit to mu...,-0.202795,0.473714
3751,"It Sucked hard, they put all the things compre...",-0.197141,0.569444
3752,The bad:,-0.700000,0.666667
3768,In Star Wars: Episode Three Anakin struggles b...,-0.057719,0.687544
3770,Star Wars Episode III Revenge of the Sith Cast...,-0.232727,0.630909

In [ ]:
# Creates a sample dataframe of 5 percent of positive reviews
positive_df_2 = positive_df.sample(frac = .05)
# Creates a sample dataframe of 5 percent of negative reviews
negative_df_2 = negative_df.sample(frac = .05)

In [ ]:
# Converts positive dataframe to csv
# Code down below was commented out because file already created 
# from pathlib import Path  
# filepath = Path('C:\\Users\\ujwal\\Downloads\\Star_Wars_Episode3_Positive_Sentiment_df.csv')  
# filepath.parent.mkdir(parents=True, exist_ok=True)  
# positive_df_2.to_csv(index=False)
# positive_df_2.to_csv(filepath)

In [ ]:
# Converts negative dataframe to csv
# Code down below was commented out because file already created 
# from pathlib import Path  
# filepath = Path('C:\\Users\\ujwal\\Downloads\\Star_Wars_Episode3_Negative_Sentiment_df.csv')  
# filepath.parent.mkdir(parents=True, exist_ok=True)  
# negative_df_2.to_csv(index=False)
# negative_df_2.to_csv(filepath)